services:
  chat-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - chat_data:/app/server/data
      - chat_uploads:/app/server/uploads
      - ./client:/app/client
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  chat_data:
  chat_uploads:
